### ISSUE TITLE
Privacy statment

### ISSUE THREAD

**Issue by Thisismydigitalself** [kennethjiang/OctoPrint-Anywhere#58]
Thank you very much for sharing this great plugin. I would love to try it out but before doing so can you please state your plugin privacy policy? What (if any) information it collects?

Thank you.

**Comment by kennethjiang** [comment]
Hi @Thisismydigitalself Thank you for asking this question.

Since this is a free app (it actually costs me money to save time-lapses in the cloud), I can't afford a lawyer to write up a privacy policy. The only thing I can say is that the app doesn't save an info (except time-lapses) about the 3D printer or the user. The information shown on the dashboard, such as IP address, are all thrown away when the window is closed.

And I don't share or resell the time-lapses when any one or any company.

Obviously what I just stated is not in legal language. But it's probably the best I can come up with. :)
