### ISSUE TITLE
Webcam framerate is much slower than on LAN

### ISSUE THREAD

**Issue by Mattwen** [kennethjiang/OctoPrint-Anywhere#85]
The frame rate on OctoPrint-Anywhere is much slower than the frame rate of my Webcam on my LAN Octoprint stream. Is there any way to fix this?

**Comment by kennethjiang** [comment]
OA streams webcam feed through the cloud (this is how you can access OctoPrint without port-forwarding), so we have to keep the frame rate low otherwise it'll cost too much internet bandwidth for most users.

However, we will be releasing a highly efficient video streaming (the same way as how YouTube streams videos) in a few weeks, which will give you 24 fps with about the same internet bandwidth requirement as current webcam feed. It'll cost $5/month to be eligible for this new video streaming (because processing video streaming in cloud is expensive). Stay tuned.

**Comment by kennethjiang** [comment]
Closing it since 25 fps streaming is officially available to everyone in OctoPrint Anywhere 1.0
